name: american_dream_messenger
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  animated_text_kit: ^4.2.2
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  pinput: ^2.2.31

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/vectors/

